import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';

const input = 'w-full rounded-lg border-gray-300 text-sm focus:border-orange-500 focus:ring-orange-500';
export default function Appointments({ services, slots, coaches, packages, members }) {
    const [memberBySlot, setMemberBySlot] = useState({});
    const service = useForm({name:'',description:'',color:'#f97316',duration_minutes:60,interval_minutes:30,credits_required:1,release_days:30,booking_deadline_hours:2,cancellation_cutoff_hours:24,is_public:true,package_ids:[]});
    const slot = useForm({appointment_service_id:services[0]?.id ?? '',coach_id:coaches[0]?.id ?? '',start_time:'',location:''});
    const submitService = e => { e.preventDefault(); service.post('/admin/appointment-services', {onSuccess:()=>service.reset()}); };
    const submitSlot = e => { e.preventDefault(); slot.post('/admin/appointment-slots', {onSuccess:()=>slot.reset('start_time','location')}); };
    return <AdminLayout title="Appointments"><Head title="Admin Appointments"/><div className="grid xl:grid-cols-2 gap-6 mb-8">
        <form onSubmit={submitService} className="bg-white rounded-xl border p-5 space-y-3"><h2 className="font-bold text-lg">New appointment service</h2><input className={input} placeholder="Service name" value={service.data.name} onChange={e=>service.setData('name',e.target.value)} required/><textarea className={input} placeholder="Description" value={service.data.description} onChange={e=>service.setData('description',e.target.value)}/><div className="grid grid-cols-2 gap-3"><label className="text-xs">Duration (minutes)<input type="number" className={input} value={service.data.duration_minutes} onChange={e=>service.setData('duration_minutes',+e.target.value)}/></label><label className="text-xs">Booking interval<input type="number" className={input} value={service.data.interval_minutes} onChange={e=>service.setData('interval_minutes',+e.target.value)}/></label><label className="text-xs">Credits per session<input type="number" className={input} value={service.data.credits_required} onChange={e=>service.setData('credits_required',+e.target.value)}/></label><label className="text-xs">Book up to days ahead<input type="number" className={input} value={service.data.release_days} onChange={e=>service.setData('release_days',+e.target.value)}/></label><label className="text-xs">Booking deadline (hours)<input type="number" className={input} value={service.data.booking_deadline_hours} onChange={e=>service.setData('booking_deadline_hours',+e.target.value)}/></label><label className="text-xs">Cancellation cutoff (hours)<input type="number" className={input} value={service.data.cancellation_cutoff_hours} onChange={e=>service.setData('cancellation_cutoff_hours',+e.target.value)}/></label></div><div><div className="text-xs font-semibold mb-1">Eligible packages (none = all active packages)</div><div className="grid grid-cols-2 gap-1 max-h-28 overflow-auto">{packages.map(p=><label key={p.id} className="text-xs flex gap-2"><input type="checkbox" checked={service.data.package_ids.includes(p.id)} onChange={e=>service.setData('package_ids',e.target.checked?[...service.data.package_ids,p.id]:service.data.package_ids.filter(id=>id!==p.id))}/>{p.name}</label>)}</div></div><button className="bg-orange-500 text-white rounded-lg px-4 py-2 font-bold">Create service</button></form>
        <form onSubmit={submitSlot} className="bg-white rounded-xl border p-5 space-y-3"><h2 className="font-bold text-lg">Add availability</h2><select className={input} value={slot.data.appointment_service_id} onChange={e=>slot.setData('appointment_service_id',e.target.value)} required><option value="">Select service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className={input} value={slot.data.coach_id} onChange={e=>slot.setData('coach_id',e.target.value)} required>{coaches.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="datetime-local" className={input} value={slot.data.start_time} onChange={e=>slot.setData('start_time',e.target.value)} required/><input className={input} placeholder="Location" value={slot.data.location} onChange={e=>slot.setData('location',e.target.value)}/><button disabled={!services.length} className="bg-orange-500 disabled:bg-gray-300 text-white rounded-lg px-4 py-2 font-bold">Add time</button></form>
    </div><div className="bg-white rounded-xl border overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold text-lg">Services & upcoming availability</h2></div><div className="p-5 flex flex-wrap gap-2 border-b">{services.map(s=><span key={s.id} className="px-3 py-2 rounded-lg bg-gray-100 text-sm"><b>{s.name}</b> · {s.duration_minutes} min · {s.credits_required} cr · {s.slots_count} slots</span>)}</div><div className="divide-y">{slots.map(s=><div key={s.id} className="p-4 flex flex-wrap items-center gap-3"><span className="w-2 h-8 rounded" style={{background:s.service.color}}/><div className="flex-1 min-w-56"><div className="font-semibold">{s.service.name} · {s.coach.name}</div><div className="text-sm text-gray-500">{new Date(s.start_time).toLocaleString()} {s.location && `· ${s.location}`}</div></div>{s.booking ? <div className="flex items-center gap-2"><span className="text-sm font-semibold text-green-600">{s.booking.user.name}</span><button onClick={()=>router.patch(`/admin/appointment-bookings/${s.booking.id}/attendance`,{status:'checked_in'})} className="text-xs font-bold text-green-700 bg-green-50 px-2 py-1 rounded">Check in</button><button onClick={()=>router.patch(`/admin/appointment-bookings/${s.booking.id}/attendance`,{status:'no_show'})} className="text-xs font-bold text-red-600 bg-red-50 px-2 py-1 rounded">No show</button><button onClick={()=>confirm('Cancel and refund this appointment?')&&router.delete(`/admin/appointment-bookings/${s.booking.id}`)} className="text-xs text-red-500">Cancel</button></div> : <div className="flex items-center gap-2"><select className="rounded-lg border-gray-300 text-xs" value={memberBySlot[s.id]??''} onChange={e=>setMemberBySlot(v=>({...v,[s.id]:e.target.value}))}><option value="">Book member…</option>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.email}</option>)}</select><button disabled={!memberBySlot[s.id]} onClick={()=>router.post(`/admin/appointment-slots/${s.id}/book`,{user_id:memberBySlot[s.id]})} className="text-xs font-bold bg-orange-500 disabled:bg-gray-300 text-white px-3 py-2 rounded-lg">Book</button><button onClick={()=>confirm('Delete this availability?')&&router.delete(`/admin/appointment-slots/${s.id}`)} className="text-xs text-red-500">Delete</button></div>}</div>)}</div></div></AdminLayout>;
}
